
#Globals
BAMsymlinks: /cluster/projects/kridelgroup/FLOMICS/TROG_99.03_ANALYSIS_20220915/BAM_symlinks/ #path to symlinks pointing to the capture DNA-Seq Tumour BAM files

#the CAPSEQ pipeline output directory
outputDIR: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/CAPSEQ_Pipeline_OUTPUT/TROG_99.03/run001/ #path specifies where the outputs of the CAPSEQ pipeline will be placed

#amplicon and target probe bed files
amplicon_bed: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/PROBES/picard_tools_amps_input.bed #the amplicon probe bed file contains the coordinates of amplicon probes in bed format, this is to be generated before the CAPSEQ pipeline is run, see CapSeq_pipeline/Scripts/001_Prepare_Amplicons_Targets_2021.R
target_bed: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/PROBES/picard_tools_targets_input.bed #the target probe bed file contains the coordinates of target probes in bed format, this is to be generated before the CAPSEQ pipeline is run, see CapSeq_pipeline/Scripts/001_Prepare_Amplicons_Targets_2021.R
# need to check on these

#hg19 reference genome files
Decomhg19Fasta: /cluster/projects/kridelgroup/FLOMICS/genome_files/human_g1k_v37.decompressed.fasta #path to decompressed hg19 human reference genome fasta file
gencodehg19GTF: /cluster/projects/kridelgroup/FLOMICS/genome_files/gencode.v19.annotation.gtf #path to gtf file of gene structure for hg19 human reference genome

#rule coverage_summary
hg19Fasta: /cluster/projects/kridelgroup/FLOMICS/genome_files/human_g1k_v37.fasta #path to hg19 human reference genome fasta file
#amplicon_interval_list: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/DATA/BCJuly2021/amplicon_interval_list/ #path to amplicon interval list which will be generated by snakemake
#target_interval_list: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/DATA/BCJuly2021/target_interval_list/ #path to target interval list which will be generated by snakemake

#rule run_Manta
MantaPath: /cluster/tools/software/centos7/manta/1.6.0/bin/configManta.py #path to Manta script
MantaDir: /cluster/tools/software/centos7/manta/1.6.0 #path to Manta directory

#rule run_CNVkit
Gene_Anno: /cluster/projects/kridelgroup/Victoria_limited_stage_analysis_2021/analysis/CNVkit/refFlat_reform.txt #path to gene annotations file used by CNVkit
CNVkitPath: /cluster/tools/software/CNVkit/0.9.3/bin/cnvkit.py #path to CNVkit script
CNVkitDir: /cluster/tools/software/CNVkit/0.9.3/ #path to CNVkit directory

#rule SNVs_mutect2_tumour_only & filter_mutect2_SNVs
gnomadRawSites: /cluster/projects/kridelgroup/RAP_ANALYSIS/af-only-gnomad.raw.sites.b37.vcf.gz #path to raw sites file which contains population allele frequencies for hg19 human reference genome

#rule VCF_annovar_annotation
Annohumandb: /cluster/tools/software/annovar/humandb/ #path to gene annotation directory, containing annotation from several databases
