
#symlinks
BAMsymlinks: /BAM_symlinks/ #path to symlinks pointing to the Capture DNA-Seq Tumour BAM files

#the CAPSEQ pipeline output directory
outputDIR: /CAPSEQ_Pipeline_OUTPUT/ #path specifies where the outputs of the CAPSEQ pipeline will be placed

#amplicon and target probe bed files
amplicon_bed: /PROBES/picard_tools_amps_input.bed #the amplicon probe bed file contains the coordinates of amplicon probes in bed format, this is to be generated before the CAPSEQ pipeline is run, see CapSeq_pipeline/Scripts/001_Prepare_Amplicons_Targets_2021.R
target_bed: /PROBES/picard_tools_targets_input.bed #the target probe bed file contains the coordinates of target probes in bed format, this is to be generated before the CAPSEQ pipeline is run, see CapSeq_pipeline/Scripts/001_Prepare_Amplicons_Targets_2021.R

#hg19 reference genome files
Decomhg19Fasta: /genome_files/human_g1k_v37.decompressed.fasta #path to decompressed hg19 human reference genome fasta file
gencodehg19GTF: /genome_files/gencode.v19.annotation.gtf #path to gtf file of gene structure for hg19 human reference genome

#rule coverage_summary
hg19Fasta: /genome_files/human_g1k_v37.fasta #path to hg19 human reference genome fasta file
#amplicon_interval_list: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/DATA/BCJuly2021/amplicon_interval_list/ #path to amplicon interval list which will be generated by snakemake
#target_interval_list: /cluster/projects/kridelgroup/FLOMICS/DATA/TargetedDNAseq/DATA/BCJuly2021/target_interval_list/ #path to target interval list which will be generated by snakemake

#rule SNVs_mutect2_tumour_only & filter_mutect2_SNVs
gnomadRawSites: /af-only-gnomad.raw.sites.b37.vcf.gz #path to raw sites file which contains population allele frequencies for hg19 human reference genome

#rule VCF_annovar_annotation
Annohumandb: /annovar/humandb/ #path to gene annotation directory, containing annotation from several databases
