# Date: 15 October 2019
# Function: Creates a venn diagram showing sample overlap. 
# Author: Anjali Silva

# Input:
# MainList: A list of length N, where each element is a vector. See example below
#           E.g., mainlist <- list(A = c(1:3),
#                                  B = c(1:10),
#                                  C = c(5:10))
#           Length(MainList) only upto five is supported. 
# Labels: A vector of length N, indicatng names for each element of list, e.g., c("A","B","C")
# FigureGenerate: Should figures be generated, default = "No". Options: "Yes", "No"
# ImageName: A character vector indicating a unique for saving the plots. 
# PNGorPDF: Output format of the image, options = "png" or "pdf"

# Output:
# VennDiagramOutput: Fitted Euler diagrams with parameters.
# VennDiagram: Diagram generated by Euler.



VennDiagram_Analysis <- function(MainList, 
                                 Labels,
                                 FigureGenerate = "Yes", 
                                 ImageName = NA, 
                                 PNGorPDF = "png") {
  
  # Loading needed packages
  library(eulerr)
  
  #
  if (length(MainList) == 2) {
    # Fit Euler diagrams using numerical optimization
    VennDiagran_Euler <- eulerr::euler(c("A" = length(MainList[[1]]), 
                                         "B" = length(MainList[[2]]), 
                                         "A&B" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]])))))
    
    # Generate venn diagram 
    VennPlot <- plot(VennDiagran_Euler, key = TRUE, counts = TRUE, quantities = TRUE, labels = Labels)
    
  } else if (length(MainList) == 3) {
    # If list on input has a length of 3
    # Fit Euler diagrams using numerical optimization
    VennDiagran_Euler <- eulerr::euler(c("A" = length(MainList[[1]]), 
                                         "B" = length(MainList[[2]]), 
                                         "C" = length(MainList[[3]]), 
                                         "A&B" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]]))), 
                                         "A&C" = length(Reduce(intersect, list(MainList[[1]], MainList[[3]]))),
                                         "B&C" = length(Reduce(intersect, list(MainList[[2]], MainList[[3]]))),
                                         "A&B&C" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]])))))
    # Generate venn diagram 
    VennPlot <- plot(VennDiagran_Euler, key = TRUE, counts = TRUE, quantities = TRUE, labels = Labels)
  } else if (length(MainList) == 4) { 
    # If list on input has a length of 4
    # Fit Euler diagrams using numerical optimization
    VennDiagran_Euler <- eulerr::euler(c("A" = length(MainList[[1]]), 
                                         "B" = length(MainList[[2]]), 
                                         "C" = length(MainList[[3]]), 
                                         "D" = length(MainList[[4]]),
                                         "A&B" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]]))), 
                                         "A&C" = length(Reduce(intersect, list(MainList[[1]], MainList[[3]]))),
                                         "A&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[4]]))), 
                                         "B&C" = length(Reduce(intersect, list(MainList[[2]], MainList[[3]]))),
                                         "B&D" = length(Reduce(intersect, list(MainList[[2]], MainList[[4]]))),
                                         "C&D" = length(Reduce(intersect, list(MainList[[3]], MainList[[4]]))),
                                         "A&B&C" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]]))),
                                         "A&B&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]]))), 
                                         "B&C&D" = length(Reduce(intersect, list(MainList[[2]], MainList[[3]], MainList[[4]]))),
                                         "A&C&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[3]], MainList[[4]]))),
                                         "A&B&C&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]], MainList[[4]])))))
            # Generate venn diagram 
    VennPlot <- plot(VennDiagran_Euler, key = TRUE, counts = TRUE, quantities = TRUE, labels = Labels)
  } else if (length(MainList) == 5) { 
    # If list on input has a length of 5
    # Fit Euler diagrams using numerical optimization
    VennDiagran_Euler <- eulerr::euler(c("A" = length(MainList[[1]]), 
                                         "B" = length(MainList[[2]]), 
                                         "C" = length(MainList[[3]]), 
                                         "D" = length(MainList[[4]]),
                                         "E" = length(MainList[[5]]),
                                         "A&B" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]]))), 
                                         "A&C" = length(Reduce(intersect, list(MainList[[1]], MainList[[3]]))),
                                         "A&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[4]]))), 
                                         "A&E" = length(Reduce(intersect, list(MainList[[1]], MainList[[5]]))), 
                                         "B&C" = length(Reduce(intersect, list(MainList[[2]], MainList[[3]]))),
                                         "B&D" = length(Reduce(intersect, list(MainList[[2]], MainList[[4]]))),
                                         "B&E" = length(Reduce(intersect, list(MainList[[2]], MainList[[5]]))), 
                                         "C&D" = length(Reduce(intersect, list(MainList[[3]], MainList[[4]]))),
                                         "C&E" = length(Reduce(intersect, list(MainList[[3]], MainList[[5]]))),
                                         "D&E" = length(Reduce(intersect, list(MainList[[4]], MainList[[5]]))),
                                         "A&B&C" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]]))),
                                         "A&B&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]]))), 
                                         "B&C&D" = length(Reduce(intersect, list(MainList[[2]], MainList[[3]], MainList[[4]]))),
                                         "A&C&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[3]], MainList[[4]]))),
                                         "A&B&C&D" = length(Reduce(intersect, list(MainList[[1]], MainList[[2]], MainList[[3]], MainList[[4]])))))
            # Generate venn diagram 
    VennPlot <- plot(VennDiagran_Euler, key = TRUE, counts = TRUE, quantities = TRUE, labels = Labels)
  } else if (length(MainList) > 5) {
    stop("\n length(MainList) only upto 5 is supported. Update code.")
  }

  RESULTS <- list(VennDiagramOutput = VennDiagran_Euler,
                  VennDiagram = VennPlot)
  
  class(RESULTS) <- "VennDiagramAnalysis_ASilva"
  return(RESULTS)
}
