# Date: 15 October 2019
# Function: Creates a venn diagram showing sample overlap. 
# Author: Anjali Silva

# Input:
# MainList: A list of length N, where each element is a vector. See example below
#           E.g., mainlist <- list(A = c(1:3),
#                                  B = c(1:10),
#                                  C = c(5:10))
#           Length(MainList) only upto five is supported. 
# Labels: A vector of length N, indicatng names for each element of list, e.g., c("A","B","C")
# FigureGenerate: Should figures be generated, default = "No". Options: "Yes", "No"
# ImageName: A character vector indicating a unique for saving the plots. 
# PNGorPDF: Output format of the image, options = "png" or "pdf"

# Output:
# VennDiagramOutput: Fitted Euler diagrams with parameters.
# VennDiagram: Diagram generated by Euler.



VennDiagramAnalysis <- function(MainList, 
                                 Labels,
                                 FigureGenerate = "Yes", 
                                 ImageName = NA, 
                                 PNGorPDF = "png") {
  
  # Loading needed packages
  library(eulerr)
  
  #
  if (length(MainList) == 2) {
    
    # Venn diagram function require unique entries.
    if(length(MainList[[1]]) != length(unique(MainList[[1]]))) {
      MainList[[1]] <- unique(MainList[[1]])
      cat("List", Labels[1], "is not unique. Only unique entries used.")
    }
    if(length(MainList[[2]]) != length(unique(MainList[[2]]))) {
      MainList[[2]] <- unique(MainList[[2]])
      cat("List", Labels[2], "is not unique. Only unique entries used.")
    }
    
    VennSetUp <- list("A" = MainList[[1]], 
                      "B" = MainList[[2]])
    names(VennSetUp) <- Labels                           
    
    # Generate venn diagram 
    VennPlot <- plot(eulerr::venn(VennSetUp))
    
  } else if (length(MainList) == 3) {
    
    # Venn diagram function require unique entries.
    if(length(MainList[[1]]) != length(unique(MainList[[1]]))) {
      MainList[[1]] <- unique(MainList[[1]])
      cat("List", Labels[1], "is not unique. Only unique entries used.")
    }
    if(length(MainList[[2]]) != length(unique(MainList[[2]]))) {
      MainList[[2]] <- unique(MainList[[2]])
      cat("List", Labels[2], "is not unique. Only unique entries used.")
    }
    if(length(MainList[[3]]) != length(unique(MainList[[3]]))) {
      MainList[[3]] <- unique(MainList[[3]])
      cat("List", Labels[3], "is not unique. Only unique entries used.")
    }
    
    VennSetUp <- list("A" = MainList[[1]], 
                       "B" = MainList[[2]],
                       "C" = MainList[[3]])
    names(VennSetUp) <- Labels                           
    VennPlot <- plot(eulerr::venn(VennSetUp))
      
  } else if (length(MainList) == 4) { 
    
    # Venn diagram function require unique entries.
    if(length(MainList[[1]]) != length(unique(MainList[[1]]))) {
      MainList[[1]] <- unique(MainList[[1]])
      cat("List", Labels[1], "is not unique. Only unique entries used.")
    }
    if(length(MainList[[2]]) != length(unique(MainList[[2]]))) {
      MainList[[2]] <- unique(MainList[[2]])
      cat("List", Labels[2], "is not unique. Only unique entries used.")
    }
    if(length(MainList[[3]]) != length(unique(MainList[[3]]))) {
      MainList[[3]] <- unique(MainList[[3]])
      cat("List", Labels[3], "is not unique. Only unique entries used.")
    }
    if(length(MainList[[4]]) != length(unique(MainList[[4]]))) {
      MainList[[4]] <- unique(MainList[[4]])
      cat("List", Labels[4], "is not unique. Only unique entries used.")
    }
    
    VennSetUp <- list("A" = MainList[[1]], 
                      "B" = MainList[[2]],
                      "C" = MainList[[3]],
                      "D" = MainList[[4]])
    names(VennSetUp) <- Labels                           
    VennPlot <- plot(eulerr::venn(VennSetUp))
    
  } else if (length(MainList) == 5) { 

    VennSetUp <- list("A" = MainList[[1]], 
                      "B" = MainList[[2]],
                      "C" = MainList[[3]],
                      "D" = MainList[[4]],
                      "E" = MainList[[5]])
    names(VennSetUp) <- Labels                           
    VennPlot <- plot(eulerr::venn(VennSetUp))
    
  } else if (length(MainList) > 5) {
    stop("\n length(MainList) only upto 5 is supported. Update code.")
  }

  RESULTS <- list(VennDiagramOutput = VennSetUp,
                  VennDiagram = VennPlot)
  
  class(RESULTS) <- "VennDiagramAnalysis_ASilva"
  return(RESULTS)
}
