
#---
# Script to re-format the read counts generated by HTSeq
# 2021 updagted 24 samples
# Ting Liu
#---

library(data.table)
library(plyr)

work_dir=getwd()
setwd(paste(work_dir,"/count_out/",sep=""))

count_files=list.files()

out=paste(work_dir,"/htseq_out/",sep="")

get_counts_clean = function(file_name){
    dat = fread(file_name)
#    dat = dat[,1:2]   
    dat=dat[grep("_PAR_Y", dat$V1, invert=TRUE),]##there are duplicated gene ids (_PAR_Y) in star output, so get rid of the _PAR_Y genes first, otherwise error message on the readDGE step
    dat=dat[grep("ENSG", dat$V1),] #get rid of the Meta tags
    dat$V1[1:nrow(dat)] = sapply(dat$V1[1:nrow(dat)], function(x){unlist(strsplit(x, "\\."))[1]}) #get rid of the postfix of the gene version
    file_out = paste(out, unlist(strsplit(file_name, "_S"))[1], "_gene_counts.txt", sep="") #'strsplit' get rid of the postfix SXX in the file name, then add the _gene_counts.txt to the end 
    write.table(dat, file=file_out, col.names=F, row.names=F, sep="\t", quote=F)
    print("done")
}

llply(count_files, get_counts_clean, .progress="text")

